<?xml version="1.0"?>
<package format="3">
  <name>kart_vehicle</name><version>0.1.0</version>
  <description>Kart vehicle control infrastructure.</description>
  <maintainer email="carbuncle01@users.noreply.github.com">carbuncle01</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rcl_interfaces</depend>
  <depend>kart_interfaces</depend>
  <depend>kart_system</depend>
  <depend>diagnostic_msgs</depend>
  <depend>std_msgs</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
